version: "0.0"

volumes:
  data:

networks:
  ijam_default:
    external: true

services:
  ijam-master:
    image: ijam-master
    container_name: "ijam-master"
    volumes:
      - ./client:/etc/client
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["/etc/client/client.sh", "-c"]
    networks:
      - ijam_default

  redis:
    image: redis:latest
    container_name: ijam-redis
    hostname: ijam-redis
    volumes:
      - data:/data
      - ./redis/data:/data
      - ./redis/conf:/etc/redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - ".env"
    environment:
      REDISCLI_AUTH: '${REDIS_MASTERPWD}'
    entrypoint: ["/etc/redis/redis.sh", "-c"]
    networks:
      - ijam_default
