version: "0.0"

volumes:
  data:

services:
  ijam-master:
    image: ijam-master
    container_name: "ijam-master"
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "-c"]
    command:
      - echo Hello, world!

  redis:
    image: redis:latest
    container_name: ijam-redis
    hostname: ijam-redis
    restart: "no"
    volumes:
      - data:/data
      - ./redis:/etc/redis
    ports:
      - 6379:6379
    environment:
      REDIS_USER: '${REDIS_USER}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    entrypoint: ["/bin/sh", "-c"]
    command:
      - redis-server --user ${REDIS_USER} +@all ~* on ">${REDIS_PASSWORD}" --include /etc/redis/redis.conf
