version: "0.0"

networks:
  ijam_default:
    driver: bridge

services:
  ijam-cc:
    image: ijam-cc
    container_name: "ijam-cc"
    env_file:
      - ".env"
    environment:
      REDISCLI_AUTH: '${REDIS_MASTERPWD}'
    volumes:
      - ./start.sh:${JAMOTA_ROOT}/start.sh
      - ./ota-portal:${JAMOTA_ROOT}/ota-portal
      - ./redis:${JAMOTA_ROOT}/redis
      - ./tools:${JAMOTA_ROOT}/tools
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
      - ${PORTAL_PORT}:${PORTAL_PORT}
      - ${CERT_SERVER_PORT}:${CERT_SERVER_PORT}
      - ${REG_SERVER_PORT}:${REG_SERVER_PORT}
      - ${STATE_SERVER_PORT}:${STATE_SERVER_PORT}
    expose:
      - ${PORTAL_PORT}
      - ${CERT_SERVER_PORT}
      - ${REG_SERVER_PORT}
      - ${STATE_SERVER_PORT}
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["${JAMOTA_ROOT}/start.sh", "-c"]
    networks:
      - ijam_default
