version: "0.0"

networks:
  ijam_default:
    driver: bridge

services:
  ijam-master:
    image: ijam-master
    container_name: "ijam-master"
    env_file:
      - ".env"
    environment:
      REDISCLI_AUTH: '${REDIS_MASTERPWD}'
    volumes:
      - ./ota-portal:${JAMOTA_ROOT}/ota-portal
      - ./redis:${JAMOTA_ROOT}/redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["${JAMOTA_ROOT}/start.sh", "-c"]
    networks:
      - ijam_default
