version: "0.0"

networks:
  ijam_default:
    driver: bridge

services:
  ijam-master:
    image: ijam-master
    container_name: "ijam-master"
    env_file:
      - ".env"
    environment:
      REDISCLI_AUTH: '${REDIS_MASTERPWD}'
    volumes:
      - ./start.sh:${JAMOTA_ROOT}/start.sh
      - ./ota-portal:${JAMOTA_ROOT}/ota-portal
      - ./redis:${JAMOTA_ROOT}/redis
      - ./ssh:${JAMOTA_ROOT}/ssh
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
      - ${PORTAL_PORT}:${PORTAL_PORT}
    expose:
      - ${PORTAL_PORT}
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["${JAMOTA_ROOT}/start.sh", "-c", "-r", "${REDIS_MODE:-none}", "-p", "${PORTAL_MODE:-none}"]
    networks:
      - ijam_default
